import { ParameterConfig, ParameterKey, WaterQualityParameters } from '../types/waterQuality';

export const PARAMETER_CONFIGS: Record<ParameterKey, ParameterConfig> = {
  // Physical Parameters
  TEMP: {
    key: 'TEMP',
    label: 'Temperature',
    abbreviation: 'TEMP',
    unit: '°C',
    section: 'physical',
    min: 0,
    max: 50,
    step: 0.5,
    defaultValue: 25,
    description: 'Thermal state of greywater affecting chemical reaction rates and microbial growth.',
    helperText: 'Typical room/ambient range: 15-35 °C.',
    optimalRange: [18, 28],
    warningRange: [10, 35],
    direction: 'range'
  },
  TUR: {
    key: 'TUR',
    label: 'Turbidity',
    abbreviation: 'TUR',
    unit: 'NTU',
    section: 'physical',
    min: 0,
    max: 100,
    step: 0.1,
    defaultValue: 8,
    description: 'Cloudiness or haziness caused by suspended solids.',
    helperText: 'Lower turbidity indicates clearer water.',
    optimalRange: [0, 5],
    warningRange: [5, 20],
    direction: 'lower_better'
  },
  TDS: {
    key: 'TDS',
    label: 'Total Dissolved Solids',
    abbreviation: 'TDS',
    unit: 'mg/L',
    section: 'physical',
    min: 0,
    max: 2000,
    step: 5,
    defaultValue: 420,
    description: 'Combined content of inorganic salts and organic matter dissolved in water.',
    helperText: 'TDS affects salinity and pipe scaling.',
    optimalRange: [0, 500],
    warningRange: [500, 1000],
    direction: 'lower_better'
  },
  DS: {
    key: 'DS',
    label: 'Dissolved Solids',
    abbreviation: 'DS',
    unit: 'mg/L',
    section: 'physical',
    min: 0,
    max: 1500,
    step: 5,
    defaultValue: 400,
    description: 'Concentration of soluble solid matter.',
    helperText: 'Related to TDS; measures dissolved particulate fraction.',
    optimalRange: [0, 450],
    warningRange: [450, 900],
    direction: 'lower_better'
  },
  EC: {
    key: 'EC',
    label: 'Conductivity',
    abbreviation: 'EC / COND',
    unit: 'µS/cm',
    section: 'physical',
    min: 0,
    max: 3000,
    step: 10,
    defaultValue: 650,
    description: 'Ability of water to conduct electrical current, indicating ionic content.',
    helperText: 'Correlates with salt and mineral concentration.',
    optimalRange: [0, 800],
    warningRange: [800, 1500],
    direction: 'lower_better'
  },
  SAL: {
    key: 'SAL',
    label: 'Salinity',
    abbreviation: 'SAL',
    unit: 'ppt',
    section: 'physical',
    min: 0,
    max: 5,
    step: 0.05,
    defaultValue: 0.4,
    description: 'Concentration of dissolved salts in water.',
    helperText: 'High salinity can damage plants and corrode fixtures.',
    optimalRange: [0, 0.5],
    warningRange: [0.5, 1.5],
    direction: 'lower_better'
  },

  // Chemical Parameters
  pH: {
    key: 'pH',
    label: 'pH',
    abbreviation: 'pH',
    unit: '—',
    section: 'chemical',
    min: 0,
    max: 14,
    step: 0.1,
    defaultValue: 7.2,
    description: 'Measure of acidity or alkalinity of the water.',
    helperText: 'Neutral water is pH 7.0. Ideal non-potable range is 6.5 to 8.5.',
    optimalRange: [6.5, 8.5],
    warningRange: [6.0, 9.0],
    direction: 'range'
  },
  DO: {
    key: 'DO',
    label: 'Dissolved Oxygen',
    abbreviation: 'DO',
    unit: 'mg/L',
    section: 'chemical',
    min: 0,
    max: 15,
    step: 0.1,
    defaultValue: 5.2,
    description: 'Amount of oxygen dissolved in water available for biological systems.',
    helperText: 'Higher DO prevents septic odors and supports biological stability.',
    optimalRange: [5.0, 12.0],
    warningRange: [3.0, 5.0],
    direction: 'higher_better'
  },
  BOD5: {
    key: 'BOD5',
    label: 'Biochemical Oxygen Demand',
    abbreviation: 'BOD₅',
    unit: 'mg/L',
    section: 'chemical',
    min: 0,
    max: 200,
    step: 1,
    defaultValue: 18,
    description: 'Amount of dissolved oxygen consumed by microorganisms decomposing organic matter over 5 days.',
    helperText: 'Indicator of biodegradable organic contamination.',
    optimalRange: [0, 20],
    warningRange: [20, 50],
    direction: 'lower_better'
  },
  COD: {
    key: 'COD',
    label: 'Chemical Oxygen Demand',
    abbreviation: 'COD',
    unit: 'mg/L',
    section: 'chemical',
    min: 0,
    max: 400,
    step: 2,
    defaultValue: 65,
    description: 'Capacity of water to consume oxygen during the decomposition of organic & inorganic matter.',
    helperText: 'Indicator of total chemically oxidizable matter.',
    optimalRange: [0, 70],
    warningRange: [70, 150],
    direction: 'lower_better'
  },
  NH4_N: {
    key: 'NH4_N',
    label: 'Ammonium / Ammonia',
    abbreviation: 'NH₄ / NH₄-N',
    unit: 'mg/L',
    section: 'chemical',
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 2.0,
    description: 'Nitrogen compound originating from detergents, soaps, and organic breakdown.',
    helperText: 'Elevated ammonia causes odors and toxicity.',
    optimalRange: [0, 2.5],
    warningRange: [2.5, 6.0],
    direction: 'lower_better'
  },
  NO3_N: {
    key: 'NO3_N',
    label: 'Nitrate',
    abbreviation: 'NO₃ / NO₃-N',
    unit: 'mg/L',
    section: 'chemical',
    min: 0,
    max: 50,
    step: 0.5,
    defaultValue: 8.0,
    description: 'Oxidized form of nitrogen compound in greywater.',
    helperText: 'Acts as a plant nutrient in irrigation, but high concentrations cause scaling.',
    optimalRange: [0, 10],
    warningRange: [10, 25],
    direction: 'lower_better'
  },
  K: {
    key: 'K',
    label: 'Potassium',
    abbreviation: 'K',
    unit: 'mg/L',
    section: 'chemical',
    min: 0,
    max: 60,
    step: 0.5,
    defaultValue: 15.0,
    description: 'Essential alkali metal ion abundant in laundry and dishwashing greywater.',
    helperText: 'Beneficial for plant growth in moderate quantities.',
    optimalRange: [0, 20],
    warningRange: [20, 35],
    direction: 'lower_better'
  },

  // Microbiological Parameter
  E_COLI: {
    key: 'E_COLI',
    label: 'E. coli',
    abbreviation: 'E. coli',
    unit: 'CFU/100 mL',
    section: 'microbiological',
    min: 0,
    max: 5000,
    step: 10,
    defaultValue: 100,
    description: 'Fecal coliform bacterium serving as a key indicator of microbiological safety and pathogens.',
    helperText: 'Crucial for determining human contact safety levels in non-potable reuse.',
    optimalRange: [0, 100],
    warningRange: [100, 500],
    direction: 'lower_better'
  }
};

export const DEMO_SAMPLE_DATA: WaterQualityParameters = {
  DO: 5.2,
  BOD5: 18,
  COD: 65,
  TDS: 420,
  EC: 650,
  pH: 7.2,
  TEMP: 27,
  SAL: 0.4,
  TUR: 8,
  DS: 400,
  NH4_N: 2.0,
  NO3_N: 8.0,
  K: 15.0,
  E_COLI: 100
};
